name: Deploy

on:
  push:
    branches: [staging]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
      - uses: actions/checkout@v2
      - name: Install composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd /var/www/hustle
            git stash
            git stash clear
            git pull origin staging
            chmod 755 -R storage bootstrap/cache
            composer i
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            npm run prod
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan optimize
            php artisan cdn:push
            php artisan refresh:cache
